version: "3.1"
services:

  api:
    build: ./server
    restart: always
    depends_on: 
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:5003

  db:
    image: mongo:4.0.5-xenial
    restart: always
