version: "3"

services:
  api:
    build: ./server
    restart: always
    depends_on: 
      - db
    env_file:
      - /home/arkadyt/code/private/env/hp.env
    ports:
      - 5003:5003

  db:
    image: mongo:4.0.5-xenial
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /home/arkadyt/volumes/mongodb_hp:/data/db
